### ISSUE TITLE
Busybox origin

### ISSUE THREAD

**Issue by dalb8** [project-voodoo/ota-rootkeeper-app#1]
Could you publish the origin for the source code of the busybox binary or maybe put the config file in this repo? We would like to publish it on f-droid.org : we have yet to publish an app with busybox built from source but hopefully soon.

**Comment by supercurio** [comment]
Hi!

You'll find this here: https://github.com/project-voodoo/buildroot_configs

On Mon, Oct 22, 2012 at 2:16 PM, dalb8 notifications@github.com wrote:

> Could you publish the origin for the source code of the busybox binary or
> maybe put the config file in this repo? We would like to publish it on
> f-droid.org : we have yet to publish an app with busybox built from
> source but hopefully soon.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/project-voodoo/ota-rootkeeper-app/issues/1.

## 

François Simond
Android developer, open source enthusiast.

http://twitter.com/supercurio http://twitter.com/#%21/supercurio
http://project-voodoo.org/

**Comment by dalb8** [comment]
Thanks, I did see that a while ago, but forgot to reply. We are looking into building Busybox with NDK (our setup doesnt support codesourcery) according to instructions in https://github.com/tias, but it doesn't seem to work. We are sorely lacking a Busybox Installer app so hopefully we can fix it soon. 

There is a working build in https://github.com/guardianproject/lildebi, which we may use for your app if it has the right applets.

**Comment by supercurio** [comment]
Nice project!

On Wed, Jan 2, 2013 at 4:54 PM, dalb8 notifications@github.com wrote:

> Thanks, I did see that a while ago, but forgot to reply. We are looking
> into building Busybox with NDK (our setup doesnt support codesourcery)
> according to instructions in https://github.com/tias, but it doesn't seem
> to work. We are sorely lacking a Busybox Installer app so hopefully we can
> fix it soon.
> 
> There is a working build in https://github.com/guardianproject/lildebi,
> which we may use for your app if it has the right applets.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/project-voodoo/ota-rootkeeper-app/issues/1#issuecomment-11812529.

## 

François Simond
Android developer, open source enthusiast.

http://twitter.com/supercurio http://twitter.com/#%21/supercurio
http://project-voodoo.org/

**Comment by dalb8** [comment]
I built busybox with this config https://github.com/tias/android-busybox-ndk/blob/master/android_ndk_defconfigPlus . I assume it covers all the applets needed and the app works fine on my phone so I'll pass to F-Droid.
